spring:
  application:
    name: spring-alibaba-demo
  ai:
    dashscope:
      api-key: sk-********
      chat:
        options:
          model: qwen-vl-max-latest
          multi-model: true
          temperature: 0.7

logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %c %M %L [%thread] %m%n'
    file: '%d{HH:mm:ss.SSS} %c %M %L [%thread] %m%n'
  level:
    org.springframework.ai.chat.client.advisor: debug