spring:
  application:
    name: spring-toolCalling-demo
  ai:
    dashscope:
      api-key: sk-**********
      chat:
        options:
          model: qwen-plus
          temperature: 0.7

logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %c %M %L [%thread] %m%n'
    file: '%d{HH:mm:ss.SSS} %c %M %L [%thread] %m%n'
  level:
    org.springframework.ai.chat.client.advisor: debug
